### ISSUE TITLE
There is a mistake in the schematic.

### ISSUE THREAD

**Issue by tokusan39** [matsujirushi/wioterminal-swd#1]
In this schematic J2-5 is connected with GND but it should be J2-6 actually.
It is fine that the board itself, J2-6 and GND are connected.

**Comment by matsujirushi** [comment]
Hi @tokusan39 ,
I am very glad that you are using wioterminal-swd.

I don't fully understand what the problem is.
I'm comparing it to the schematic for Wio Terminal, and it looks fine to me.

**Left: Wio Terminal schematic**  
**Right: wioterminal-swd schematic**  

![image](https://user-images.githubusercontent.com/8079404/121273363-10ddfa80-c903-11eb-8ae1-ea0571eb756a.png)


Could you please explain more?

**Comment by tokusan39** [comment]
Hi Takashi-san,

I'm really sorry. It seems I was confused on this.
Your are perfectory right.

Best Regards,
Tokuyama
